# -*- coding: utf-8 -*-
"""predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riverH5QOzpO04lDEQLmsMKPUOoB4R3S
"""

from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
import torch

# Load model
print("Loading AI model...")
model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Simple example
text = "Who is Srishail Mukundan"
print(f"\nStarting text: '{text}'")
print("\nGenerating word by word...\n")

# Generate 5 words, one at a time
current_text = text
for step in range(2):
    print(f"--- Step {step + 1} ---")
    print(f"Current: '{current_text}'")

    # Encode current text
    input_ids = tokenizer.encode(current_text, return_tensors="pt")

    output_ids = model.generate(
    input_ids,
    max_new_tokens=5,     # How many words/tokens to generate in this chunk
    do_sample=True,         # Use sampling instead of greedy search
    top_k=50,               # Top-K sampling
    top_p=0.95,             # Nucleus sampling
    repetition_penalty=1.2,
    temperature=0.8,        # Level of creativity
    pad_token_id=tokenizer.eos_token_id
)

    new_tokens = output_ids[0][input_ids.shape[-1]:]
    new_chunk_text = tokenizer.decode(new_tokens, skip_special_tokens=True)

    # 4. Update the history
    current_text += "\n" + new_chunk_text


    print(f"Added: {new_chunk_text}")
    print(f"Full Context now: {current_text}\n")






    # end generation when there is a period
    if generated_text == {'.'}:
      current_text += " "
      #print(f"\nFinal generated text: '{current_text}'")
      #break
for step in range(1):
    print(f"--- Step {step + 1} ---")
    print(f"Current: '{current_text}'")

    # Encode current text
    input_ids = tokenizer.encode(current_text, return_tensors="pt")

    output_ids = model.generate(
    input_ids,
    max_new_tokens=8,     # How many words/tokens to generate in this chunk
    do_sample=True,         # Use sampling instead of greedy search
    top_k=50,               # Top-K sampling
    top_p=0.95,             # Nucleus sampling
    repetition_penalty=1.2,
    temperature=0.7,        # Level of creativity
    pad_token_id=tokenizer.eos_token_id
)

    new_tokens = output_ids[0][input_ids.shape[-1]:]
    new_chunk_text = tokenizer.decode(new_tokens, skip_special_tokens=True)

    # 4. Update the history
    current_text += "\n" + new_chunk_text


    print(f"Added: {new_chunk_text}")
    print(f"Full Context now: {current_text}\n")






    # end generation when there is a period
    if generated_text == {'.'}:
      current_text += " "
      #print(f"\nFinal generated text: '{current_text}'")
      #break

print(f"\nFinal generated text: '{current_text}'")

